version: "3.8"

services:
  mc:
    build:
      context: .
      dockerfile: Dockerfile-mc
    image: ghcr.io/nincodedo/rhc-ocw-mc:6.1.0
    env_file:
      - motd_override.env
      - docker.env
    environment:
      DIFFICULTY: 'hard'
      HARDCORE: 'true'
      OVERRIDE_SERVER_PROPERTIES: 'true'
      ICON: 'https://cdn.discordapp.com/icons/109466144993210368/a_63bcc148bca7700101d1fb6b9522d638.png'
      RESOURCE_PACK: 'https://ocw-rhc.services.nincodedo.dev/v1/resource-pack'
      RESOURCE_PACK_SHA1: '8787be18b94fa6d01278452ada2f6f1ef0741f85'
      #OVERRIDE_ICON: 'true'
      MEMORY: '3G'
      BROADCAST_RCON_TO_OPS: 'false'
      FUNCTION_PERMISSION_LEVEL: '4'
      ENABLE_COMMAND_BLOCK: 'true'
      SPAWN_PROTECTION: '0'
      ENABLE_AUTOPAUSE: 'true'
      MAX_TICK_TIME: "-1"
      AUTOPAUSE_TIMEOUT_EST: '30'
      AUTOPAUSE_TIMEOUT_INIT: '120'
      TYPE: 'FABRIC'
      REMOVE_OLD_MODS: 'true'
      VERSION: '1.20.1'
      INITIAL_ENABLED_PACKS: 'bundle'
      RCON_CMDS_STARTUP: |-
        gamerule doDaylightCycle false
        chunky radius 3000
        chunky start
        chunky continue
      RCON_CMDS_FIRST_CONNECT: |-
        gamerule doDaylightCycle true
        chunky pause
      RCON_CMDS_LAST_DISCONNECT: |-
        gamerule doDaylightCycle false
        chunky continue
    volumes:
      - mc_server:/data
      - mc_mod_configs:/config
    container_name: mc
    tty: true
    stdin_open: true
    labels:
      dev.nincodedo.gameservercommander.game: "Minecraft"
      dev.nincodedo.gameservercommander.group: "MC-RHC"
      dev.nincodedo.gameservercommander.name: "OCW Minecraft RHC"
      dev.nincodedo.gameservercommander.description: "OCW Radical Hardcore 6.1.0 - Minecraft 1.20.1"
      dev.nincodedo.gameservercommander.connection_info: "games.nincodedo.dev"
      com.centurylinklabs.watchtower.enable: false
  log-watcher:
    build:
      context: .
      dockerfile: Dockerfile-log-watcher
      labels:
        - "com.centurylinklabs.watchtower.enable=false"
    image: ghcr.io/nincodedo/rhc-ocw:6.1.0
    container_name: log-watcher
    env_file:
      - docker.env
    environment:
      TZ: 'CST6CDT'
      MC_CONTAINER_NAME: 'mc'
    secrets:
      - discord_webhook
    volumes:
      - mc_server:/data
      - mc_mod_configs:/config
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      dev.nincodedo.gameservercommander.group: "MC-RHC"
      com.centurylinklabs.watchtower.enable: false
  mc-test:
    build:
      context: .
      dockerfile: Dockerfile-mc
    image: ghcr.io/nincodedo/rhc-ocw-mc:unstable
    env_file:
      - motd_override.env
      - docker.env
    environment:
      DIFFICULTY: 'hard'
      HARDCORE: 'true'
      OVERRIDE_SERVER_PROPERTIES: 'true'
      ICON: 'https://cdn.discordapp.com/icons/109466144993210368/a_63bcc148bca7700101d1fb6b9522d638.png'
      RESOURCE_PACK_SHA1: '8787be18b94fa6d01278452ada2f6f1ef0741f85'
      #OVERRIDE_ICON: 'true'
      MEMORY: '2G'
      BROADCAST_RCON_TO_OPS: 'false'
      FUNCTION_PERMISSION_LEVEL: '4'
      ENABLE_COMMAND_BLOCK: 'true'
      SPAWN_PROTECTION: '0'
      ENABLE_AUTOPAUSE: 'true'
      MAX_TICK_TIME: "-1"
      AUTOPAUSE_TIMEOUT_EST: '30'
      AUTOPAUSE_TIMEOUT_INIT: '120'
      TYPE: 'FABRIC'
      REMOVE_OLD_MODS: 'true'
      VERSION: '1.20.1'
      INITIAL_ENABLED_PACKS: 'bundle'
      RESOURCE_PACK: 'https://ocw-rhc.services.nincodedo.dev/v1/resource-pack?type=beta'
      RCON_CMDS_STARTUP: |-
        gamerule doDaylightCycle false
      RCON_CMDS_FIRST_CONNECT: |-
        gamerule doDaylightCycle true
      RCON_CMDS_LAST_DISCONNECT: |-
        gamerule doDaylightCycle false
    volumes:
      - mc_server_test:/data
    container_name: mc-test
    tty: true
    stdin_open: true
    labels:
      com.centurylinklabs.watchtower.enable: false
  log-watcher-test:
    build:
      context: .
      dockerfile: Dockerfile-log-watcher
      labels:
        - "com.centurylinklabs.watchtower.enable=false"
    image: ghcr.io/nincodedo/rhc-ocw:unstable
    container_name: log-watcher-test
    env_file:
      - docker.env
    environment:
      TZ: 'CST6CDT'
      MC_CONTAINER_NAME: 'mc-test'
    volumes:
      - mc_server_test:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: false
  router:
    image: itzg/mc-router
    container_name: router
    ports:
      - "25565:25565"
    command: --mapping=games.nincodedo.dev=mc:25565,rhctest.nincodedo.dev=mc-test:25565
volumes:
  mc_server:
  mc_server_test:
  mc_mod_configs:
secrets:
  discord_webhook:
    file: ./secrets/discord_webhook.txt
