version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
    - "25565:25565"
    - "25575:25575"
    - "25575:25575/udp"
    - "24454:24454/udp"
    env_file:
      - motd_override.env
      - docker.env
    environment:
      EULA: 'true'
      TZ: 'America/Chicago'
      DIFFICULTY: 'hard'
      HARDCORE: 'true'
      OPS: 'nincodedo'
      OVERRIDE_SERVER_PROPERTIES: 'true'
      ICON: 'https://cdn.discordapp.com/icons/109466144993210368/a_63bcc148bca7700101d1fb6b9522d638.png'
      OVERRIDE_ICON: 'true'
      MEMORY: '2G'
      FUNCTION_PERMISSION_LEVEL: '4'
      SPAWN_PROTECTION: '0'
      ENABLE_AUTOPAUSE: 'true'
      MAX_TICK_TIME: "-1"
      AUTOPAUSE_TIMEOUT_EST: '30'
      AUTOPAUSE_TIMEOUT_INIT: '120'
      TYPE: 'FABRIC'
      REMOVE_OLD_MODS: 'true'
      VERSION: '1.18.2'
    volumes:
      - mc_server:/data
      - mc_mods:/mods
      - mc_mod_configs:/config
    container_name: mc
    tty: true
    stdin_open: true
    labels:
      dev.nincodedo.gameservercommander.game: "Minecraft"
      dev.nincodedo.gameservercommander.group: "MC-RHC"
      dev.nincodedo.gameservercommander.name: "OCW Minecraft RHC"
      dev.nincodedo.gameservercommander.description: "OCW Radical Hardcore Minecraft 1.18.2"
  log-watcher:
    build:
      context: .
      labels:
        - "com.centurylinklabs.watchtower.enable=false"
    image: ghcr.io/nincodedo/rhc-ocw:latest
    container_name: log-watcher
    env_file:
      - docker.env
    environment:
      TZ: 'CST6CDT'
    secrets:
      - discord_webhook
    volumes:
    - mc_server:/data
    - mc_mods:/mods
    - mc_mod_configs:/config
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
      dev.nincodedo.gameservercommander.group: "MC-RHC"
      com.centurylinklabs.watchtower.enable: false
volumes:
  mc_server:
  mc_mods:
  mc_mod_configs:
secrets:
  discord_webhook:
    file: ./secrets/discord_webhook.txt
