on:
  push:
    tags:
      - "*"
name: Release Build
jobs:
  buildlw:
    name: Build Log Watcher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_ACTIONS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-log-watcher
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ghcr.io/nincodedo/rhc-ocw:latest
            ghcr.io/nincodedo/rhc-ocw:${{ github.sha }}
            ghcr.io/nincodedo/rhc-ocw:${{ github.ref_name }}
  buildmc:
    name: Build Minecraft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_ACTIONS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-mc
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ghcr.io/nincodedo/rhc-ocw-mc:latest
            ghcr.io/nincodedo/rhc-ocw-mc:${{ github.sha }}
            ghcr.io/nincodedo/rhc-ocw-mc:${{ github.ref_name }}
  createRelease:
    needs: [ buildlw, buildmc ]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          discussion_category_name: 'Announcements'
  