on:
  push:
    branches:
      - main
name: Main Build
jobs:
  buildlw:
    name: Build Log Watcher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_ACTIONS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-log-watcher
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ghcr.io/nincodedo/rhc-ocw:unstable
            ghcr.io/nincodedo/rhc-ocw:${{ github.sha }}
  buildmc:
    name: Build Minecraft
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_ACTIONS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-mc
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ghcr.io/nincodedo/rhc-ocw-mc:unstable
            ghcr.io/nincodedo/rhc-ocw-mc:${{ github.sha }}
